---
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        exclude: .github/.*
        files: \.(yaml|yml)$
        types: [file, yaml]
        always_run: true
        entry: yamllint --strict .

  - repo: https://github.com/markdownlint/markdownlint.git
    rev: v0.12.0
    hooks:
      - id: markdownlint
        exclude: .github/.*
        types: [file, markdown]
        files: \.(md|rst)$
        always_run: true
